### ISSUE TITLE
Hashes for byte runs

### ISSUE THREAD

**Issue by ajnelson** [dfxml-working-group/dfxml_schema#19]
DFXML has been used in the past for distributing sector hashes.  The [hashdeep](https://github.com/jessek/hashdeep) tool family still does this, by adding hashes as child elements of `byte_run` elements, e.g.:

```
...
<byte_run file_offset='252416' len='512'>
  <hashdigest type='MD5'>94c9a12d937c5f1eb9baf8255f7a16af</hashdigest>
</byte_run>
<byte_run file_offset='252928' len='397'>
  <hashdigest type='MD5'>5777047d17dc3dff8ef8380a8595b670</hashdigest>
</byte_run>
...
```

I've received a request to make this a standard behavior option.  Structurally and programmatically, I prefer hashdeep's approach to the original Fiwalk approach of adding a long stream of sector hashes after the `byte_runs` element.

**Comment by ajnelson-nist** [comment]
This had been included in [https://github.com/dfxml-working-group/dfxml_schema/commit/b4829b49].
